const advancedPhrasesData = [
    // 1. 고급 접속사 & 연결어 (Konnektor) - 20개
    {id:1, c:"Konnektor", g:"Vorausgesetzt, dass...", m:"~라는 조건 하에", s:"Vorausgesetzt, dass das Wetter mitspielt, findet das Konzert statt."},
    {id:2, c:"Konnektor", g:"Es sei denn, dass...", m:"~하지 않는 한 / ~가 아니라면", s:"Ich werde morgen kommen, es sei denn, dass ich krank werde."},
    {id:3, c:"Konnektor", g:"Infolge (+Gen)...", m:"~의 결과로", s:"Infolge des starken Regens kam es zu Überschwemmungen."},
    {id:4, c:"Konnektor", g:"Angesichts (+Gen)...", m:"~를 고려하면 / ~에 직면하여", s:"Angesichts der aktuellen Situation müssen wir unsere Strategie ändern."},
    {id:5, c:"Konnektor", g:"Ungeachtet (+Gen)...", m:"~에도 불구하고", s:"Ungeachtet aller Warnungen fuhr er fort."},
    {id:6, c:"Konnektor", g:"In Bezug auf...", m:"~와 관련하여", s:"Wir müssen eine Entscheidung in Bezug auf das Budget treffen."},
    {id:7, c:"Konnektor", g:"Hinsichtlich (+Gen)...", m:"~의 측면에서", s:"Hinsichtlich der Qualität gibt es keine Kompromisse."},
    {id:8, c:"Konnektor", g:"Anstatt dass...", m:"~하는 대신에", s:"Anstatt dass er sich entschuldigte, stritt er den Fehler ab."},
    {id:9, c:"Konnektor", g:"Je [비교급], desto [비교급]...", m:"~하면 할수록 더욱 ~하다", s:"Je länger man wartet, desto schwieriger wird es."},
    {id:10, c:"Konnektor", g:"Sowohl... als auch...", m:"A뿐만 아니라 B도", s:"Sowohl der Preis als auch die Leistung überzeugen."},
    {id:11, c:"Konnektor", g:"Weder... noch...", m:"A도 B도 아닌", s:"Er spricht weder Deutsch noch Englisch."},
    {id:12, c:"Konnektor", g:"Entweder... oder...", m:"A 아니면 B", s:"Wir müssen entweder sparen oder mehr verdienen."},
    {id:13, c:"Konnektor", g:"Zwar... aber...", m:"비록 ~이긴 하지만 ~이다", s:"Zwar war es anstrengend, aber es hat sich gelohnt."},
    {id:14, c:"Konnektor", g:"Nicht nur..., sondern auch...", m:"A뿐만 아니라 B 역시", s:"Er ist nicht nur intelligent, sondern auch sehr fleißig."},
    {id:15, c:"Konnektor", g:"Einerseits..., andererseits...", m:"한편으로는..., 다른 한편으로는...", s:"Einerseits ist die Lösung einfach, andererseits kostet sie viel."},
    {id:16, c:"Konnektor", g:"Demzufolge...", m:"그 결과로 / 따라서", s:"Er hat hart gearbeitet; demzufolge hat er die Prüfung bestanden."},
    {id:17, c:"Konnektor", g:"Infolgedessen...", m:"그 때문에", s:"Es gab einen Unfall. Infolgedessen war die Straße gesperrt."},
    {id:18, c:"Konnektor", g:"Nichtsdestotrotz...", m:"그럼에도 불구하고", s:"Es gab Probleme, nichtsdestotrotz haben wir es geschafft."},
    {id:19, c:"Konnektor", g:"Vielmehr...", m:"오히려 / 차라리", s:"Er ist kein Freund; vielmehr ist er ein Konkurrent."},
    {id:20, c:"Konnektor", g:"Ganz zu schweigen von...", m:"~은 말할 것도 없이", s:"Die Kosten sind hoch, ganz zu schweigen von der Zeit."},

    // 2. 명사+동사 결합 (Nomen-Verb) - 30개
    {id:21, c:"Nomen-Verb", g:"In Anspruch nehmen", m:"이용하다 / 활용하다", s:"Wir sollten die Gelegenheit in Anspruch nehmen."},
    {id:22, c:"Nomen-Verb", g:"Eine Entscheidung treffen", m:"결정을 내리다", s:"Die Geschäftsführung muss eine Entscheidung treffen."},
    {id:23, c:"Nomen-Verb", g:"Abschied nehmen von", m:"~와 작별하다", s:"Wir müssen Abschied nehmen von alten Gewohnheiten."},
    {id:24, c:"Nomen-Verb", g:"In Erwägung ziehen", m:"고려하다 / 검토하다", s:"Wir werden Ihren Vorschlag in Erwägung ziehen."},
    {id:25, c:"Nomen-Verb", g:"Einen Antrag stellen", m:"신청하다", s:"Sie müssen einen Antrag stellen für das Stipendium."},
    {id:26, c:"Nomen-Verb", g:"Kritik üben an", m:"~를 비판하다", s:"Er übt Kritik an der neuen Regelung."},
    {id:27, c:"Nomen-Verb", g:"Einfluss nehmen auf", m:"~에 영향을 미치다", s:"Das Wetter nimmt Einfluss auf die Ernte."},
    {id:28, c:"Nomen-Verb", g:"Bezug nehmen auf", m:"~를 참조하다 / 언급하다", s:"Ich nehme Bezug auf unser gestriges Gespräch."},
    {id:29, c:"Nomen-Verb", g:"Zum Abschluss bringen", m:"끝내다 / 마무리 짓다", s:"Das Projekt soll nächste Woche zum Abschluss gebracht werden."},
    {id:30, c:"Nomen-Verb", g:"Zur Verfügung stehen", m:"준비되어 있다 / 이용 가능하다", s:"Die Daten stehen Ihnen zur Verfügung."},
    {id:31, c:"Nomen-Verb", g:"In Frage kommen", m:"고려 대상이다 / 가능하다", s:"Eine sofortige Lösung kommt nicht in Frage."},
    {id:32, c:"Nomen-Verb", g:"Unter Beweis stellen", m:"증명하다", s:"Er hat seine Kompetenz unter Beweis gestellt."},
    {id:33, c:"Nomen-Verb", g:"Einen Kompromiss schließen", m:"타협하다", s:"Wir mussten einen Kompromiss schließen, um weiterzukommen."},
    {id:34, c:"Nomen-Verb", g:"Verantwortung tragen für", m:"~에 책임을 지다", s:"Sie trägt die Verantwortung für das Team."},
    {id:35, c:"Nomen-Verb", g:"In Kontakt treten mit", m:"~와 연락하다", s:"Wir werden bald in Kontakt treten mit Ihnen."},
    {id:36, c:"Nomen-Verb", g:"Vorbereitungen treffen", m:"준비를 하다", s:"Wir treffen Vorbereitungen für die Konferenz."},
    {id:37, c:"Nomen-Verb", g:"Einen Rat geben", m:"조언하다", s:"Kannst du mir bitte einen Rat geben?"},
    {id:38, c:"Nomen-Verb", g:"Zur Sprache bringen", m:"화제로 삼다 / 말을 꺼내다", s:"Das Problem muss zur Sprache gebracht werden."},
    {id:39, c:"Nomen-Verb", g:"Wert legen auf", m:"~를 중요하게 여기다", s:"Wir legen Wert auf Qualität."},
    {id:40, c:"Nomen-Verb", g:"Interesse wecken an", m:"~에 흥미를 불러일으키다", s:"Der Vortrag hat Interesse geweckt an dem Thema."},
    {id:41, c:"Nomen-Verb", g:"Einen Beitrag leisten zu", m:"~에 기여하다", s:"Jeder kann einen Beitrag leisten zu einer besseren Umwelt."},
    {id:42, c:"Nomen-Verb", g:"In Erfüllung gehen", m:"실현되다 / 이루어지다", s:"Sein größter Wunsch ist in Erfüllung gegangen."},
    {id:43, c:"Nomen-Verb", g:"Im Irrtum sein", m:"착각하고 있다", s:"Sie sind im Irrtum, wenn Sie das glauben."},
    {id:44, c:"Nomen-Verb", g:"Maßnahmen ergreifen", m:"조치를 취하다", s:"Die Regierung muss schnell Maßnahmen ergreifen."},
    {id:45, c:"Nomen-Verb", g:"Einen Entschluss fassen", m:"결심하다", s:"Nach langer Überlegung hat er einen Entschluss gefasst."},
    {id:46, c:"Nomen-Verb", g:"Auf Distanz gehen zu", m:"~와 거리를 두다", s:"Er ging auf Distanz zu seinen alten Freunden."},
    {id:47, c:"Nomen-Verb", g:"Flucht ergreifen", m:"도망치다", s:"Die Täter mussten Flucht ergreifen."},
    {id:48, c:"Nomen-Verb", g:"In Aussicht stellen", m:"약속하다 / 전망을 제시하다", s:"Das Unternehmen hat eine Gehaltserhöhung in Aussicht gestellt."},
    {id:49, c:"Nomen-Verb", g:"Glauben schenken", m:"~를 믿다", s:"Ich kann seinen Worten keinen Glauben schenken."},
    {id:50, c:"Nomen-Verb", g:"Verständnis aufbringen für", m:"~를 이해하다", s:"Wir müssen Verständnis aufbringen für die Situation."},

    // 3. 논리적 토론 (Diskussion) - 20개
    {id:51, c:"Diskussion", g:"Daraus lässt sich schließen, dass...", m:"그것으로부터 ~라는 결론이 나온다", s:"Daraus lässt sich schließen, dass die Investition erfolgreich war."},
    {id:52, c:"Diskussion", g:"Es steht außer Frage, dass...", m:"~는 의문의 여지가 없다", s:"Es steht außer Frage, dass Bildung wichtig ist."},
    {id:53, c:"Diskussion", g:"Ich vertrete den Standpunkt, dass...", m:"나는 ~라는 입장을 견지한다", s:"Ich vertrete den Standpunkt, dass mehr Umweltschutz nötig ist."},
    {id:54, c:"Diskussion", g:"Man muss in Betracht ziehen, dass...", m:"~를 고려해야만 한다", s:"Man muss in Betracht ziehen, dass die Kosten steigen werden."},
    {id:55, c:"Diskussion", g:"Im Gegensatz dazu...", m:"그와는 반대로", s:"Wir haben gute Ergebnisse erzielt. Im Gegensatz dazu steht die Konkurrenz."},
    {id:56, c:"Diskussion", g:"In diesem Zusammenhang...", m:"이러한 맥락에서", s:"Das ist ein wichtiges Detail. In diesem Zusammenhang möchte ich erwähnen..."},
    {id:57, c:"Diskussion", g:"Es lässt sich nicht leugnen, dass...", m:"~라는 점을 부정할 수 없다", s:"Es lässt sich nicht leugnen, dass die Technologie Vorteile bringt."},
    {id:58, c:"Diskussion", g:"Zusammenfassend lässt sich sagen...", m:"요약해서 말하자면", s:"Zusammenfassend lässt sich sagen, dass wir unser Ziel erreicht haben."},
    {id:59, c:"Diskussion", g:"Ein wesentlicher Aspekt ist...", m:"핵심적인 측면은 ~이다", s:"Ein wesentlicher Aspekt ist die langfristige Planung."},
    {id:60, c:"Diskussion", g:"Es kommt darauf an, inwiefern...", m:"어느 정도로 ~인지에 달려 있다", s:"Es kommt darauf an, inwiefern die Regierung das Problem löst."},
    {id:61, c:"Diskussion", g:"Ich möchte betonen, dass...", m:"~를 강조하고 싶습니다", s:"Ich möchte betonen, dass die Zeit ein entscheidender Faktor ist."},
    {id:62, c:"Diskussion", g:"Es herrscht Einigkeit darüber, dass...", m:"~에 대해 합의가 이루어져 있다", s:"Es herrscht Einigkeit darüber, dass wir handeln müssen."},
    {id:63, c:"Diskussion", g:"Das Argument sticht nicht.", m:"그 논거는 설득력이 없다", s:"Tut mir leid, aber das Argument sticht nicht."},
    {id:64, c:"Diskussion", g:"Es liegt auf der Hand, dass...", m:"~는 자명하다", s:"Es liegt auf der Hand, dass wir die Regeln einhalten müssen."},
    {id:65, c:"Diskussion", g:"Hervorzuheben ist, dass...", m:"~를 특히 강조해야 한다", s:"Hervorzuheben ist, dass die Zusammenarbeit essentiell war."},
    {id:66, c:"Diskussion", g:"Ich bezweifle, dass...", m:"~인지 의심스럽다", s:"Ich bezweifle, dass diese Methode funktioniert."},
    {id:67, c:"Diskussion", g:"Wenn man davon ausgeht, dass...", m:"~라고 가정한다면", s:"Wenn man davon ausgeht, dass die Prognose stimmt, dann..."},
    {id:68, c:"Diskussion", g:"Es ist unumstritten, dass...", m:"~는 논란의 여지가 없다", s:"Es ist unumstritten, dass die Erde rund ist."},
    {id:69, c:"Diskussion", g:"Soweit ich beurteilen kann...", m:"내가 판단할 수 있는 한", s:"Soweit ich beurteilen kann, ist der Plan gut."},
    {id:70, c:"Diskussion", g:"Alles in allem...", m:"모든 것을 고려할 때", s:"Alles in allem war es eine erfolgreiche Veranstaltung."},

    // 4. 양태 불변사 & 부사 (Modalpartikel) - 15개
    {id:71, c:"Partikel", g:"Eigentlich...", m:"사실은 / 실은", s:"Eigentlich wollte ich heute früher gehen."},
    {id:72, c:"Partikel", g:"Anscheinend...", m:"보아하니 / 겉보기에는", s:"Anscheinend hat er die Nachricht nicht bekommen."},
    {id:73, c:"Partikel", g:"Offensichtlich...", m:"분명히 / 명백하게", s:"Offensichtlich liegt hier ein Missverständnis vor."},
    {id:74, c:"Partikel", g:"Vermutlich...", m:"아마도 / 추측건대", s:"Vermutlich wird die Lieferung morgen ankommen."},
    {id:75, c:"Partikel", g:"Gegebenenfalls...", m:"필요한 경우에", s:"Wir müssen einen Plan B haben, gegebenenfalls."},
    {id:76, c:"Partikel", g:"In der Regel...", m:"보통 / 일반적으로", s:"In der Regel beginnt die Arbeit um neun Uhr."},
    {id:77, c:"Partikel", g:"Glücklicherweise...", m:"다행히도", s:"Glücklicherweise hat es nicht geregnet."},
    {id:78, c:"Partikel", g:"Bedauerlicherweise...", m:"유감스럽게도", s:"Bedauerlicherweise können wir den Termin nicht halten."},
    {id:79, c:"Partikel", g:"Gelegentlich...", m:"가끔 / 때때로", s:"Gelegentlich gehe ich ins Theater."},
    {id:80, c:"Partikel", g:"Stufenweise...", m:"단계적으로", s:"Die Reform wird stufenweise eingeführt."},
    {id:81, c:"Partikel", g:"Halt...", m:"어쩔 수 없이 ~다 / 그냥", s:"Das ist halt so."},
    {id:82, c:"Partikel", g:"Eben...", m:"바로 그거야 / 그러니까 말이야", s:"Du hast eben das Problem erkannt."},
    {id:83, c:"Partikel", g:"Doch...", m:"강조: 정말로 / ~잖아", s:"Du hast mir doch versprochen zu helfen!"},
    {id:84, c:"Partikel", g:"Ja...", m:"놀람/당연함: ~이네! / 당연히", s:"Das weiß ja jeder!"},
    {id:85, c:"Partikel", g:"Wohl...", m:"아마도 ~일 것이다", s:"Das wird wohl das Beste sein."},

    // 5. 관용구 (Redewendung) - 15개
    {id:86, c:"Redewendung", g:"Auf Nummer sicher gehen", m:"안전한 길을 택하다", s:"Wir sollten auf Nummer sicher gehen und alles doppelt prüfen."},
    {id:87, c:"Redewendung", g:"Den Faden verlieren", m:"말의 흐름을 놓치다", s:"Entschuldigung, ich habe den Faden verloren."},
    {id:88, c:"Redewendung", g:"Etwas unter die Lupe nehmen", m:"면밀히 조사하다", s:"Wir müssen die Zahlen unter die Lupe nehmen."},
    {id:89, c:"Redewendung", g:"Ein Auge zudrücken", m:"눈감아 주다", s:"Kannst du bei dieser Kleinigkeit ein Auge zudrücken?"},
    {id:90, c:"Redewendung", g:"In der Klemme stecken", m:"곤경에 처하다", s:"Seit dem Fehler stecken wir in der Klemme."},
    {id:91, c:"Redewendung", g:"Zwei Fliegen mit einer Klappe schlagen", m:"일거양득 (두 마리 토끼)", s:"Mit diesem Plan können wir zwei Fliegen mit einer Klappe schlagen."},
    {id:92, c:"Redewendung", g:"Auf dem Laufenden bleiben", m:"최신 소식을 계속 파악하다", s:"Es ist wichtig, immer auf dem Laufenden zu bleiben."},
    {id:93, c:"Redewendung", g:"Den Teufel an die Wand malen", m:"불길한 소리를 하다", s:"Hör auf, den Teufel an die Wand zu malen!"},
    {id:94, c:"Redewendung", g:"Die Kirche im Dorf lassen", m:"과장하지 않다", s:"Bitte lass die Kirche im Dorf und übertreibe nicht."},
    {id:95, c:"Redewendung", g:"In Kauf nehmen", m:"감수하다", s:"Man muss die Risiken in Kauf nehmen."},
    {id:96, c:"Redewendung", g:"Grünes Licht geben", m:"허가를 내주다", s:"Der Chef hat grünes Licht gegeben für das Projekt."},
    {id:97, c:"Redewendung", g:"Das Kind beim Namen nennen", m:"직설적으로 말하다", s:"Wir sollten das Kind beim Namen nennen und ehrlich sein."},
    {id:98, c:"Redewendung", g:"Den Nagel auf den Kopf treffen", m:"정곡을 찌르다", s:"Mit deiner Aussage hast du den Nagel auf den Kopf getroffen."},
    {id:99, c:"Redewendung", g:"Sich ein Bild machen von...", m:"~에 대해 파악하다", s:"Ich möchte mir ein Bild machen von der Situation vor Ort."},
    {id:100, c:"Redewendung", g:"Hand in Hand gehen mit...", m:"~와 밀접하게 관련되다", s:"Wirtschaftswachstum muss Hand in Hand gehen mit Umweltschutz."}
];