const redemittelData = [
    // 1. 기본 의사 표현 (Basis)
    {id:1, c:"Basis", p:"Ich möchte...", m:"~하고 싶어요", s:"Ich möchte Kaffee trinken.", t:"커피 마시고 싶어요."},
    {id:2, c:"Basis", p:"Ich hätte gerne...", m:"~를 원합니다 (주문)", s:"Ich hätte gerne eine Pizza.", t:"피자 한 판을 원합니다."},
    {id:3, c:"Basis", p:"Ich brauche...", m:"~가 필요해요", s:"Ich brauche deine Hilfe.", t:"네 도움이 필요해."},
    {id:4, c:"Basis", p:"Ich suche...", m:"~를 찾고 있어요", s:"Ich suche meinen Schlüssel.", t:"내 열쇠를 찾고 있어요."},
    {id:5, c:"Basis", p:"Ich habe...", m:"나는 ~를 가지고 있어요", s:"Ich habe einen Hund.", t:"나는 개를 한 마리 가지고 있어요."},
    {id:6, c:"Basis", p:"Ich bin...", m:"나는 ~입니다", s:"Ich bin Student.", t:"저는 학생입니다."},
    {id:7, c:"Basis", p:"Ich kann...", m:"나는 ~를 할 수 있어요", s:"Ich kann gut Deutsch sprechen.", t:"저는 독일어를 잘 말할 수 있어요."},
    {id:8, c:"Basis", p:"Ich muss...", m:"나는 ~를 해야 해요", s:"Ich muss jetzt gehen.", t:"저는 지금 가야 해요."},
    {id:9, c:"Basis", p:"Ich darf...", m:"나는 ~해도 돼요", s:"Ich darf hier parken.", t:"저는 여기에 주차해도 됩니다."},
    {id:10, c:"Basis", p:"Ich will...", m:"나는 ~를 원해요", s:"Ich will das Buch lesen.", t:"나는 그 책을 읽고 싶어요."},
    {id:11, c:"Basis", p:"Ich weiß...", m:"나는 ~를 알아요", s:"Ich weiß die Antwort.", t:"나는 그 답을 알아요."},
    {id:12, c:"Basis", p:"Ich weiß nicht, ob...", m:"~인지 잘 모르겠어요", s:"Ich weiß nicht, ob er kommt.", t:"그가 올지 잘 모르겠어요."},
    {id:13, c:"Basis", p:"Ich verstehe...", m:"나는 ~를 이해해요", s:"Ich verstehe das Problem.", t:"저는 그 문제를 이해합니다."},
    {id:14, c:"Basis", p:"Ich glaube...", m:"내 생각에는 ~인 것 같아요", s:"Ich glaube, es wird regnen.", t:"내 생각엔 비가 올 것 같아요."},
    {id:15, c:"Basis", p:"Ich denke...", m:"~라고 생각해요", s:"Ich denke, du hast recht.", t:"네가 맞다고 생각해요."},
    {id:16, c:"Basis", p:"Ich hoffe...", m:"~하기를 바라요", s:"Ich hoffe, alles ist gut.", t:"모든 것이 잘 되기를 바라요."},
    {id:17, c:"Basis", p:"Ich freue mich auf...", m:"~가 기대돼요", s:"Ich freue mich auf den Urlaub.", t:"휴가가 기대돼요."},
    {id:18, c:"Basis", p:"Ich erinnere mich an...", m:"~가 기억나요", s:"Ich erinnere mich an unser erstes Treffen.", t:"우리의 첫 만남이 기억나요."},
    {id:19, c:"Basis", p:"Ich interessiere mich für...", m:"~에 관심이 있어요", s:"Ich interessiere mich für Geschichte.", t:"저는 역사에 관심이 있어요."},
    {id:20, c:"Basis", p:"Ich habe Angst vor...", m:"~가 두려워요", s:"Ich habe Angst vor Spinnen.", t:"저는 거미가 두려워요."},

    // 2. 질문 및 정보 요청 (Frage)
    {id:21, c:"Frage", p:"Was ist...?", m:"~가 무엇인가요?", s:"Was ist das?", t:"이것은 무엇인가요?"},
    {id:22, c:"Frage", p:"Wo ist...?", m:"~가 어디 있나요?", s:"Wo ist die Toilette?", t:"화장실이 어디 있나요?"},
    {id:23, c:"Frage", p:"Wie geht...?", m:"~는 어떻게 하나요?", s:"Wie geht das Spiel?", t:"이 게임은 어떻게 하나요?"},
    {id:24, c:"Frage", p:"Wann beginnt...?", m:"~는 언제 시작하나요?", s:"Wann beginnt der Film?", t:"영화는 언제 시작하나요?"},
    {id:25, c:"Frage", p:"Warum ist...?", m:"왜 ~인가요?", s:"Warum bist du traurig?", t:"너는 왜 슬프니?"},
    {id:26, c:"Frage", p:"Wer ist...?", m:"누가 ~인가요?", s:"Wer ist dieser Mann?", t:"이 남자는 누구인가요?"},
    {id:27, c:"Frage", p:"Wie viel kostet...?", m:"얼마인가요?", s:"Wie viel kostet der Kaffee?", t:"커피는 얼마인가요?"},
    {id:28, c:"Frage", p:"Wie lange dauert...?", m:"시간이 얼마나 걸리나요?", s:"Wie lange dauert die Fahrt?", t:"운전하는 데 시간이 얼마나 걸리나요?"},
    {id:29, c:"Frage", p:"Können Sie mir helfen?", m:"도와주실 수 있나요?", s:"Können Sie mir helfen, bitte?", t:"저 좀 도와주실 수 있나요?"},
    {id:30, c:"Frage", p:"Darf ich fragen...?", m:"물어봐도 될까요?", s:"Darf ich fragen, wie alt du bist?", t:"몇 살인지 물어봐도 될까요?"},
    {id:31, c:"Frage", p:"Wissen Sie, wo...?", m:"~가 어디인지 아세요?", s:"Wissen Sie, wo die Post ist?", t:"우체국이 어디 있는지 아세요?"},
    {id:32, c:"Frage", p:"Könnten Sie das wiederholen?", m:"다시 말씀해 주시겠어요?", s:"Könnten Sie das wiederholen, bitte?", t:"다시 말씀해 주시겠어요?"},
    {id:33, c:"Frage", p:"Was bedeutet...?", m:"~는 무슨 뜻인가요?", s:"Was bedeutet dieses Wort?", t:"이 단어는 무슨 뜻인가요?"},
    {id:34, c:"Frage", p:"Wie sagt man ... auf Deutsch?", m:"...를 독일어로 뭐라고 하나요?", s:"Wie sagt man 'hello' auf Deutsch?", t:"'hello'를 독일어로 뭐라고 하나요?"},
    {id:35, c:"Frage", p:"Gibt es hier...?", m:"여기에 ~가 있나요?", s:"Gibt es hier WLAN?", t:"여기에 와이파이가 있나요?"},
    {id:36, c:"Frage", p:"Haben Sie...?", m:"~를 가지고 계신가요?", s:"Haben Sie ein Feuerzeug?", t:"라이터를 가지고 계신가요?"},
    {id:37, c:"Frage", p:"Was machst du...?", m:"너 ~뭐 하니?", s:"Was machst du am Wochenende?", t:"너 주말에 뭐 하니?"},
    {id:38, c:"Frage", p:"Was denkst du über...?", m:"~에 대해 어떻게 생각해?", s:"Was denkst du über den neuen Film?", t:"새 영화에 대해 어떻게 생각해?"},
    {id:39, c:"Frage", p:"Wie findest du...?", m:"~는 어떤 것 같아?", s:"Wie findest du mein neues Kleid?", t:"내 새 드레스는 어떤 것 같아?"},
    {id:40, c:"Frage", p:"Bist du sicher?", m:"확실해?", s:"Bist du sicher, dass das stimmt?", t:"그것이 사실이라는 것이 확실해?"},

    // 3. 의견 공유 (Meinung)
    {id:41, c:"Meinung", p:"Meiner Meinung nach...", m:"제 의견으로는...", s:"Meiner Meinung nach ist das die beste Lösung.", t:"제 의견으로는 이것이 최고의 해결책입니다."},
    {id:42, c:"Meinung", p:"Ich bin der Meinung, dass...", m:"제 의견은 ~라는 것입니다", s:"Ich bin der Meinung, dass wir mehr sparen sollten.", t:"제 의견은 우리가 더 저축해야 한다는 것입니다."},
    {id:43, c:"Meinung", p:"Ich bin einverstanden.", m:"동의합니다", s:"Ich bin einverstanden mit deinem Vorschlag.", t:"당신의 제안에 동의합니다."},
    {id:44, c:"Meinung", p:"Ich stimme dir zu.", m:"네 말에 동의해", s:"Ich stimme dir zu, das ist wichtig.", t:"네 말에 동의해, 이건 중요해."},
    {id:45, c:"Meinung", p:"Das stimmt.", m:"맞아요", s:"Das stimmt, das habe ich vergessen.", t:"맞아요, 그걸 잊고 있었어요."},
    {id:46, c:"Meinung", p:"Das ist wahr.", m:"그건 사실이에요", s:"Das ist wahr, er ist sehr talentiert.", t:"그건 사실이에요, 그는 매우 재능이 있어요."},
    {id:47, c:"Meinung", p:"Ich sehe das anders.", m:"난 다르게 생각해", s:"Ich sehe das anders, ich bin nicht überzeugt.", t:"난 다르게 생각해, 납득이 안 돼."},
    {id:48, c:"Meinung", p:"Das ist mir egal.", m:"난 상관없어", s:"Das ist mir egal, du kannst wählen.", t:"난 상관없어, 네가 선택할 수 있어."},
    {id:49, c:"Meinung", p:"Es kommt darauf an.", m:"경우에 따라 달라요", s:"Es kommt darauf an, wie viel Zeit wir haben.", t:"우리가 얼마나 많은 시간이 있는지에 따라 달라요."},
    {id:50, c:"Meinung", p:"Einerseits..., andererseits...", m:"한편으로는..., 다른 한편으로는...", s:"Einerseits ist es teuer, andererseits ist es sehr gut.", t:"한편으로는 비싸지만, 다른 한편으로는 매우 좋아요."},
    {id:51, c:"Meinung", p:"Ich bin mir nicht sicher.", m:"확실하지 않아요", s:"Ich bin mir nicht sicher, ob ich mitkommen kann.", t:"제가 함께 갈 수 있을지 확실하지 않아요."},
    {id:52, c:"Meinung", p:"Das ist ein guter Punkt.", m:"좋은 지적이에요", s:"Das ist ein guter Punkt, darüber habe ich nicht nachgedacht.", t:"좋은 지적이에요, 그 점에 대해 생각하지 못했어요."},
    {id:53, c:"Meinung", p:"Ehrlich gesagt...", m:"솔직히 말해서...", s:"Ehrlich gesagt, mag ich das nicht.", t:"솔직히 말해서, 저는 그것을 좋아하지 않아요."},
    {id:54, c:"Meinung", p:"Vielleicht hast du recht.", m:"아마 네 말이 맞을지도 몰라", s:"Vielleicht hast du recht, wir sollten warten.", t:"아마 네 말이 맞을지도 몰라, 우리는 기다려야 해."},
    {id:55, c:"Meinung", p:"Genau!", m:"맞아! 바로 그거야!", s:"Genau! Das ist es, was ich meine!", t:"맞아! 바로 그거야, 내가 말하려던 게!"},

    // 4. 제안 및 약속 (Vorschlag)
    {id:56, c:"Vorschlag", p:"Hast du Lust auf...?", m:"~할 마음 있어?", s:"Hast du Lust auf Kino?", t:"영화 보러 갈 마음 있어?"},
    {id:57, c:"Vorschlag", p:"Wollen wir...?", m:"우리 ~할까?", s:"Wollen wir heute Abend kochen?", t:"우리 오늘 저녁에 요리할까?"},
    {id:58, c:"Vorschlag", p:"Sollen wir...?", m:"우리 ~해야 할까?", s:"Sollen wir einen Plan machen?", t:"우리 계획을 세워야 할까요?"},
    {id:59, c:"Vorschlag", p:"Wie wäre es mit...?", m:"~는 어때?", s:"Wie wäre es mit einem Spaziergang?", t:"산책은 어때?"},
    {id:60, c:"Vorschlag", p:"Können wir uns treffen?", m:"우리 만날 수 있을까?", s:"Können wir uns morgen treffen?", t:"우리 내일 만날 수 있을까?"},
    {id:61, c:"Vorschlag", p:"Wann hast du Zeit?", m:"언제 시간 돼?", s:"Wann hast du Zeit nächste Woche?", t:"너 다음 주 언제 시간 돼?"},
    {id:62, c:"Vorschlag", p:"Ich lade dich ein.", m:"초대할게 / 내가 낼게", s:"Ich lade dich zum Abendessen ein.", t:"내가 저녁 식사에 너를 초대할게."},
    {id:63, c:"Vorschlag", p:"Das klingt gut.", m:"좋게 들리네 / 좋아", s:"Das klingt gut, lass uns das machen.", t:"좋게 들리네, 그렇게 하자."},
    {id:64, c:"Vorschlag", p:"Leider kann ich nicht.", m:"아쉽지만 안 되겠어", s:"Leider kann ich nicht kommen.", t:"아쉽지만 갈 수 없겠어."},
    {id:65, c:"Vorschlag", p:"Ich habe schon etwas vor.", m:"이미 선약이 있어요", s:"Tut mir leid, ich habe schon etwas vor.", t:"미안해, 이미 선약이 있어."},
    {id:66, c:"Vorschlag", p:"Passt es dir am...?", m:"~요일/시에 시간 괜찮아?", s:"Passt es dir am Freitag um sieben?", t:"금요일 7시에 시간 괜찮아?"},
    {id:67, c:"Vorschlag", p:"Abgemacht!", m:"결정됐어! / 좋아!", s:"Abgemacht! Wir sehen uns dann!", t:"결정됐어! 그럼 그때 보자!"},
    {id:68, c:"Vorschlag", p:"Ich freue mich darauf.", m:"기대하고 있을게", s:"Ich freue mich darauf, dich zu sehen.", t:"너를 볼 것을 기대하고 있을게."},
    {id:69, c:"Vorschlag", p:"Lass uns...", m:"우리 ~하자", s:"Lass uns ins Museum gehen.", t:"우리 박물관에 가자."},
    {id:70, c:"Vorschlag", p:"Wir könnten...", m:"우리 ~할 수도 있어", s:"Wir könnten ins Restaurant gehen.", t:"우리 식당에 갈 수도 있어."},

    // 5. 문장 연결 (Konnektor)
    {id:71, c:"Konnektor", p:"...weil...", m:"왜냐하면 ~니까", s:"Ich lerne Deutsch, weil ich in Deutschland arbeiten will.", t:"저는 독일에서 일하고 싶기 때문에 독일어를 배웁니다."},
    {id:72, c:"Konnektor", p:"...dass...", m:"~라는 것", s:"Ich denke, dass du Recht hast.", t:"나는 네가 맞다고 생각한다."},
    {id:73, c:"Konnektor", p:"...wenn...", m:"만약 ~라면 / ~할 때", s:"Ruf mich an, wenn du ankommst.", t:"네가 도착하면 나에게 전화해."},
    {id:74, c:"Konnektor", p:"...obwohl...", m:"비록 ~일지라도", s:"Obwohl es regnet, gehe ich spazieren.", t:"비록 비가 오지만, 나는 산책하러 갑니다."},
    {id:75, c:"Konnektor", p:"...damit...", m:"~하기 위해서", s:"Ich spare Geld, damit ich reisen kann.", t:"저는 여행할 수 있도록 돈을 모읍니다."},
    {id:76, c:"Konnektor", p:"...um ... zu...", m:"~하기 위해", s:"Ich gehe in die Küche, um Kaffee zu kochen.", t:"나는 커피를 끓이기 위해 부엌에 갑니다."},
    {id:77, c:"Konnektor", p:"...deshalb...", m:"그래서 / 그 때문에", s:"Es war kalt, deshalb bin ich zu Hause geblieben.", t:"추웠어요, 그래서 저는 집에 머물렀습니다."},
    {id:78, c:"Konnektor", p:"...trotzdem...", m:"그럼에도 불구하고", s:"Ich war müde, trotzdem habe ich trainiert.", t:"저는 피곤했지만, 그럼에도 불구하고 운동했습니다."},
    {id:79, c:"Konnektor", p:"Entweder... oder...", m:"A 아니면 B", s:"Entweder wir gehen ins Kino oder ins Theater.", t:"우리는 영화관 아니면 극장에 간다."},
    {id:80, c:"Konnektor", p:"Nicht nur..., sondern auch...", m:"A뿐만 아니라 B도", s:"Er spricht nicht nur Deutsch, sondern auch Spanisch.", t:"그는 독일어뿐만 아니라 스페인어도 말한다."},
    {id:81, c:"Konnektor", p:"Sowohl... als auch...", m:"A도 B도 둘 다", s:"Sie mag sowohl Katzen als auch Hunde.", t:"그녀는 고양이와 개 둘 다 좋아한다."},
    {id:82, c:"Konnektor", p:"Bevor ich...", m:"~하기 전에", s:"Bevor ich schlafe, lese ich ein Buch.", t:"저는 잠자리에 들기 전에 책을 읽습니다."},
    {id:83, c:"Konnektor", p:"Nachdem ich...", m:"~한 후에", s:"Nachdem ich gegessen habe, ruhe ich mich aus.", t:"저는 식사한 후에 쉽니다."},
    {id:84, c:"Konnektor", p:"Seitdem ich...", m:"~한 이래로", s:"Seitdem ich hier wohne, bin ich glücklicher.", t:"제가 여기에 사는 이래로 더 행복합니다."},
    {id:85, c:"Konnektor", p:"Solange...", m:"~하는 동안은", s:"Solange du lernst, mache ich das Abendessen.", t:"네가 공부하는 동안은 내가 저녁 식사를 만들게."},

    // 6. 일상 및 감정 (Alltag)
    {id:86, c:"Alltag", p:"Es geht mir gut.", m:"잘 지내요", s:"Danke der Nachfrage, es geht mir gut.", t:"물어봐 줘서 고마워요, 잘 지내요."},
    {id:87, c:"Alltag", p:"Ich bin müde.", m:"피곤해요", s:"Ich bin heute sehr müde.", t:"저는 오늘 너무 피곤해요."},
    {id:88, c:"Alltag", p:"Ich habe Hunger/Durst.", m:"배고파요/목말라요", s:"Ich habe Hunger, lass uns essen gehen.", t:"배고파요, 우리 밥 먹으러 가요."},
    {id:89, c:"Alltag", p:"Es tut mir leid.", m:"미안합니다", s:"Es tut mir leid für die Verspätung.", t:"늦어서 미안합니다."},
    {id:90, c:"Alltag", p:"Kein Problem.", m:"문제없어요", s:"Kein Problem, ich kann warten.", t:"문제없어요, 저는 기다릴 수 있어요."},
    {id:91, c:"Alltag", p:"Macht nichts.", m:"상관없어요", s:"Macht nichts, das passiert.", t:"상관없어요, 그런 일도 있죠."},
    {id:92, c:"Alltag", p:"Viel Glück!", m:"행운을 빌어!", s:"Viel Glück bei deiner Prüfung!", t:"네 시험에 행운을 빌어!"},
    {id:93, c:"Alltag", p:"Gute Besserung!", m:"빨리 쾌차하세요!", s:"Gute Besserung, ich hoffe, du wirst bald gesund!", t:"빨리 쾌차하세요, 곧 건강해지기를 바라요!"},
    {id:94, c:"Alltag", p:"Schönen Tag noch!", m:"좋은 하루 보내세요!", s:"Schönen Tag noch! Bis bald!", t:"좋은 하루 보내세요! 곧 봐요!"},
    {id:95, c:"Alltag", p:"Gleichfalls.", m:"당신도요", s:"Ich wünsche dir einen schönen Tag. - Gleichfalls.", t:"좋은 하루 보내. - 당신도요."},
    {id:96, c:"Alltag", p:"Wie schade!", m:"정말 아쉽다!", s:"Wie schade! Ich hätte dich gerne getroffen.", t:"정말 아쉽다! 너를 만나고 싶었는데."},
    {id:97, c:"Alltag", p:"Wahnsinn!", m:"대박! 말도 안 돼!", s:"Wahnsinn! Das ist unglaublich!", t:"대박! 믿을 수 없어!"},
    {id:98, c:"Alltag", p:"Echt?", m:"진짜?", s:"Echt? Das wusste ich nicht.", t:"진짜? 그건 몰랐어."},
    {id:99, c:"Alltag", p:"Natürlich.", m:"당연하지", s:"Natürlich können wir dir helfen.", t:"당연히 우리가 너를 도울 수 있지."},
    {id:100, c:"Alltag", p:"Bis bald!", m:"곧 봐!", s:"Bis bald! Wir sehen uns morgen.", t:"곧 봐! 우리 내일 만나."}
];